### ISSUE TITLE
Payment Methodes

### ISSUE THREAD

**Issue by klarlichter** [i-ways/magento2-paypal-plus#2]
Hello,

did paypal plus module magento 2 support the following payment methodes:
> Paypal Standard
> Paypal Invoice (without PP Login)
> Paypal Credit Card (without PP Login)
> Paypal Dirct Debit (without PP Login)

Please confirm. 
Could you also provide a Screen how it should looks on Magento Checkout?
We still using OneStepCheckout so maybe I need made it compatible with OSC. 

Hope you can let me know that answers.

**Comment by hilrob** [comment]
Hi,

OSC is not jet supported. 
I have attached a screen from our staging which should answer your questions.
![image](https://cloud.githubusercontent.com/assets/895713/17701421/0fcdac1a-63ca-11e6-8451-f6b333346e1d.png)

For further support please use our Helpdesk at: https://i-ways.atlassian.net/servicedesk/customer/portal/3

We will close Github issues.

Greetings
